name: Publish NuGet

on:
  [workflow_dispatch]
  
env:
  SOLUTION_FILE_PATH: Toolkit.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
    
    - name: Pack
      run: dotnet pack ${{ env.SOLUTION_FILE_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-build
      
    - name: Publish
      run: dotnet nuget push .\Outcompute.Toolkit.Core.CodeGenerator\bin\Release\Outcompute.Toolkit.Core.CodeGenerator.1.0.0.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.int.nugettest.org/v3/index.json   
